[
  {
    "ClassName": "Npgsql.PostgresException",
    "Message": "External component has thrown an exception.",
    "Data": {
      "Severity": "ERROR",
      "InvariantSeverity": "ERROR",
      "SqlState": "57014",
      "MessageText": "canceling statement due to user request",
      "File": "postgres.c",
      "Line": "3124",
      "Routine": "ProcessInterrupts"
    },
    "HelpURL": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2147467259,
    "Source": "Npgsql",
    "WatsonBuckets": null,
    "Severity": "ERROR",
    "InvariantSeverity": "ERROR",
    "SqlState": "57014",
    "MessageText": "canceling statement due to user request",
    "Detail": null,
    "Hint": null,
    "Position": 0,
    "InternalPosition": 0,
    "InternalQuery": null,
    "Where": null,
    "SchemaName": null,
    "TableName": null,
    "ColumnName": null,
    "DataTypeName": null,
    "ConstraintName": null,
    "File": "postgres.c",
    "Line": "3124",
    "Routine": "ProcessInterrupts"
  }
]